package com.example.meetingmanager.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.meetingmanager.bean.UserBean;
import com.example.meetingmanager.bean.EquipmentBean;
import com.example.meetingmanager.bean.MeetingBean;
import com.example.meetingmanager.bean.MeetingRoomBean;

import com.example.meetingmanager.greendao.UserBeanDao;
import com.example.meetingmanager.greendao.EquipmentBeanDao;
import com.example.meetingmanager.greendao.MeetingBeanDao;
import com.example.meetingmanager.greendao.MeetingRoomBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig equipmentBeanDaoConfig;
    private final DaoConfig meetingBeanDaoConfig;
    private final DaoConfig meetingRoomBeanDaoConfig;

    private final UserBeanDao userBeanDao;
    private final EquipmentBeanDao equipmentBeanDao;
    private final MeetingBeanDao meetingBeanDao;
    private final MeetingRoomBeanDao meetingRoomBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        equipmentBeanDaoConfig = daoConfigMap.get(EquipmentBeanDao.class).clone();
        equipmentBeanDaoConfig.initIdentityScope(type);

        meetingBeanDaoConfig = daoConfigMap.get(MeetingBeanDao.class).clone();
        meetingBeanDaoConfig.initIdentityScope(type);

        meetingRoomBeanDaoConfig = daoConfigMap.get(MeetingRoomBeanDao.class).clone();
        meetingRoomBeanDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        equipmentBeanDao = new EquipmentBeanDao(equipmentBeanDaoConfig, this);
        meetingBeanDao = new MeetingBeanDao(meetingBeanDaoConfig, this);
        meetingRoomBeanDao = new MeetingRoomBeanDao(meetingRoomBeanDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(EquipmentBean.class, equipmentBeanDao);
        registerDao(MeetingBean.class, meetingBeanDao);
        registerDao(MeetingRoomBean.class, meetingRoomBeanDao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        equipmentBeanDaoConfig.clearIdentityScope();
        meetingBeanDaoConfig.clearIdentityScope();
        meetingRoomBeanDaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public EquipmentBeanDao getEquipmentBeanDao() {
        return equipmentBeanDao;
    }

    public MeetingBeanDao getMeetingBeanDao() {
        return meetingBeanDao;
    }

    public MeetingRoomBeanDao getMeetingRoomBeanDao() {
        return meetingRoomBeanDao;
    }

}
